# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 06:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(blank=True, help_text='license plate', max_length=10, null=True, verbose_name='license plate')),
                ('color', models.CharField(blank=True, help_text='color of car', max_length=30, null=True, verbose_name='color of car')),
                ('brand', models.CharField(blank=True, help_text='brand of car', max_length=128, null=True, verbose_name='brand of car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="the car's owner")),
            ],
            options={
                'db_table': 'Cars',
            },
        ),
    ]
