# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 06:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, unique=True)),
                ('bind_at', models.DateTimeField(auto_now_add=True, verbose_name='bind at')),
                ('fob_num', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='camera name or tag')),
            ],
        ),
        migrations.CreateModel(
            name='CameraFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='if true this friend can get alert and streaming', verbose_name='can get alert and stream')),
                ('camera', models.ManyToManyField(related_name='camera_id', to='client.Camera')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CameraFriend',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'Domain',
            },
        ),
        migrations.CreateModel(
            name='ProductSerial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, unique=True)),
                ('be_used', models.BooleanField(default=False, help_text='if be used or binded. set true', verbose_name='be used')),
            ],
            options={
                'db_table': 'ProductSerial',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Domain'),
        ),
        migrations.AddField(
            model_name='camera',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="the camera's owner"),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(through='client.CameraFriend', to=settings.AUTH_USER_MODEL),
        ),
    ]
