# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20180223_0606'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='camera',
            table='Camera',
        ),
    ]
